name: 'Checking Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checking branch
        if: github.base_ref == 'main' && github.head_ref != 'Dev'
        run: |
          echo "ERROR: You are only able to merge to main from dev."
          exit 1
